name: Workflow

on: [push]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog backend
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swipl-branch: devel
          swipl-version: latest
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
      - name: Checkout Logtalk application to be tested
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run the application tests
        run: |
          logtalk_tester -f tap -c xml
          xsltproc --stringparam prefix work/$(basename $GITHUB_REPOSITORY)/$(basename $GITHUB_REPOSITORY)/ --stringparam url https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA -o coverage_report.html coverage_report.xml
      - name: Upload TAP report
        uses: actions/upload-artifact@master
        with:
          name: tap-report
          path: tap_report.txt
      - name: Upload code coverage report
        uses: actions/upload-artifact@master
        with:
          name: code-coverage-report
          path: coverage_report.html
      - name: Copy code coverage report
        run: |
          mkdir -p public
          cp coverage_report.html public/
      - name: Publish code coverage report
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: public
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: Generate the application documentation
        run: |
          swilgt -g "{loader,lgtdoc(loader)},lgtdoc::directory('.')" -t halt
          cd xml_docs
          printf 'n\nTicTacToeTalk\nPaul Brown\n\n\n' | lgt2rst -s -t "TicTacToeTalk"
          make html
          cd _build/html
          zip -r ../../../docs.zip *
      - name: Upload documentation
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs.zip
      - name: Generate the application diagrams
        run: |
          swilgt -g "{loader,diagrams(loader)},diagrams::directory('.')" -t halt
          lgt2svg
          zip diagrams.zip *.svg
      - name: Upload diagrams
        uses: actions/upload-artifact@master
        with:
          name: diagrams
          path: diagrams.zip
      - name: Create QLF files for the game
        run: |
          mkdir ~/collect
          $LOGTALKHOME/scripts/embedding/swipl/swipl_logtalk_qlf.sh -c -d $HOME/collect -l $HOME/loader.lgt -s $LOGTALKUSER/scripts/embedding/settings-embedding-sample.lgt -p $LOGTALKUSER/paths/paths.pl
      - name: Upload Logtalk QLF file
        uses: actions/upload-artifact@master
        with:
          name: logtalk.qlf
          path: /home/runner/collect/logtalk.qlf
      - name: Upload application QLF file
        uses: actions/upload-artifact@master
        with:
          name: application.qlf
          path: /home/runner/collect/application.qlf
